### ISSUE TITLE
Pod install error

### ISSUE THREAD

**Issue by wudb** [lukakerr/twig#4]
pod install then error:

### Error

```
RuntimeError - [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:321:in `configure_with_plist'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:262:in `new_from_plist'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:299:in `each'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:296:in `each'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:262:in `new_from_plist'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:299:in `each'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:296:in `each'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:262:in `new_from_plist'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:203:in `initialize_from_file'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:103:in `open'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/analyzer.rb:918:in `block (2 levels) in inspect_targets_to_integrate'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/analyzer.rb:917:in `each'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/analyzer.rb:917:in `block in inspect_targets_to_integrate'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/analyzer.rb:912:in `inspect_targets_to_integrate'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/analyzer.rb:78:in `analyze'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:243:in `analyze'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:116:in `install!'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/command/install.rb:41:in `run'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/command.rb:52:in `run'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.5.0/bin/pod:55:in `<top (required)>'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/bin/pod:23:in `load'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/nc-wudb/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by ChandniSharma** [comment]
how to update it , no command work properly ...
